### ISSUE TITLE
Gmediafinder Can No Longer Play Youtube Videos 

### ISSUE THREAD

**Issue by martinkg** [smolleyes/StreamStudio#1]
sorry, are you the same software developer of gmediafinder2 ?
can you have a look on the following ticket:
https://github.com/smolleyes/gmediafinder2/issues/6

**Comment by smolleyes** [comment]
hi

yes i am but gmediafinder is a very old project now, my focus is on 
streamstudio (really better..) so i can t update gmf anymore :)

try it :)

sorry, thanks

**Comment by martinkg** [comment]
ok, i will take StreamStudio
