### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by MatMoul** [smolleyes/StreamStudio#10]
I love this project but streamstudio.me and streamstudio.cc is down from several weeks.
How can I build this project form here?

**Comment by Draxler** [comment]
I don't know if this project is completley dead but i found an answer 1 year old from ''the owner'' of this project and this is what he thinks about this project at that time;

He wrote in italian lang (if i'm not mistaken). 
Here are 2 screenshots: 1st in Italian lang and  2nd in English (Google translation)

![screenshot_2](https://user-images.githubusercontent.com/7681671/28958746-d6c9b4e2-78f7-11e7-8c4c-cea1cf432c50.png)

![screenshot_3](https://user-images.githubusercontent.com/7681671/28958765-e82626d0-78f7-11e7-9340-5978bbfe08bc.png)

Even then he talked about working on another similar project which will be better mantained as this one and all new ideas will be in this new project he had in mind and that this project StreamStudio wouldn't get much new additions for that very reason and only basic stuff will be manintained..  (this is at least how i understood his post at that time .. anyway see it for your self and you'll come to your own conclousions.

Here is the source URL where owner talked about that:
https://github.com/smolleyes/StreamStudio/issues/8

Regards

**Comment by MatMoul** [comment]
streamstudio.cc seem alive and my streamstudio has dowloaded new plugins...
Is this a good evolution or is risquy because no message from the author...

**Comment by smolleyes** [comment]
hello

sorry for late reply, i dont spend a lot of time on this anymore since code is a nightmare lol but i still update it sometimes :) 

thanks !
