### ISSUE TITLE
german language file

### ISSUE THREAD

**Issue by martinkg** [smolleyes/StreamStudio#3]
attached is the german  language file for StreamStudio.
https://www.dropbox.com/s/5l49jvbg5eoppzc/de.json?dl=0

**Comment by martinkg** [comment]
small update with fixes.
https://www.dropbox.com/s/5l49jvbg5eoppzc/de.json?dl=0

**Comment by smolleyes** [comment]
Hello
I made an update yesterday and enabled the german why not fixing translation on transifex :p ?
--
Envoyé via l'application myMail pour Android
samedi, 07 février 2015, 00:42PM +01:00 de martinkg <notifications@github.com>:
small update with fixes.
https://www.dropbox.com/s/5l49jvbg5eoppzc/de.json?dl=0

**Comment by smolleyes** [comment]
hello

just added some strings to translate :)

tel me when done (if you can be fast...) so i can send another update 
for the software

thanks

**Comment by martinkg** [comment]
I am done now with german translation.

**Comment by smolleyes** [comment]
ok thanks i ll update ss tomorrow :)

**Comment by smolleyes** [comment]
hi m8

added some few strings again (normally last add for few times)

can have a look ?

thx !
