### ISSUE TITLE
Chrome OS support

### ISSUE THREAD

**Issue by HLFH** [smolleyes/StreamStudio#4]
Hi,
It would be cool to support Chrome (and Chrome OS).

**Comment by smolleyes** [comment]
hi

have some console logs to show with it ?

thanks

**Comment by HLFH** [comment]
@smolleyes Coucou ubunteros.

Je comprends pas. StreamStudio, c'est pas une application desktop qui ne fonctionne donc pas dans le navigateur en tant qu'extension ou webapplication ? Donc, pourquoi faut-il fournir des logs de console ? Ou bien j'ai mal compris comment fonctionne StreamStudio.

**Comment by smolleyes** [comment]
ola

moi qui ait dû mal comprendre la tienne alors

non ça ne peut effectivement pas marcher en tant qu extension chrome, 
trop compliqué :/ ou il faut attendre que d autres projets soient plus 
matures
et pour chrome os je sais pas comment marche cet os

++

**Comment by HLFH** [comment]
StreamStudio pourra peut-être s'inspirer de Popcorn Time dès qu'ils [le sortent sur Chrome](https://discuss.popcorntime.io/t/native-pct-app-extension-for-chrome-os-chromebook-chromebox/14003).

**Comment by smolleyes** [comment]
peut pas regarder ton lien mais on verra à ce moment là oui :)

**Comment by HLFH** [comment]
@smolleyes Je ferme. Popcorn TIme a été abandonné. Butter Project n'est pas pertinent. J'ai brické mon Chromebook avec des mauvaises manips sur Coreboot. **J'ai migré vers StreamStudio sur Windows :)** Comme je préfère à l'alternative Stremio qui n'est pas open source.
