### ISSUE TITLE
how to start StreamStudio on Linux (fedora 21)

### ISSUE THREAD

**Issue by martinkg** [smolleyes/StreamStudio#5]
can you tell me, how to start StreamStudio on Linux ?

**Comment by smolleyes** [comment]
hello

just run the streamtudio binary file in the zip... (download it from streamstudio.me)

you only have the sources files on the git, need to add node-webkit to complete the software (my own builds are here : http://streamstudio.me/StreamStudio/nw12)

launch it thru shell if nothing happen to see what s wrong, never tried it on fedora

thanks
