### ISSUE TITLE
Windows installer issue

### ISSUE THREAD

**Issue by blue-melon** [smolleyes/StreamStudio#6]
Hi, 
the windows installer fails to create directories on my computer : error 206:nom de ficher ou extension trop long. (too long file name).

Setup was unable to create the directory "C:\Program File(x86)\StreamStudio\node_modules\googleapis\node_modules\gapitoken\node_modules\jws\node_modules\tap\node_modules\runforcecover\node_modules\bunker\node_modules\burrito\node_modules\uglify-js\test\unit\compress"

**Comment by smolleyes** [comment]
hi

ok i ll fix this asap ! sorry

**Comment by smolleyes** [comment]
humm are you sure to have the latest setup ?

i dont  have node_modules\googleapis in my sources

**Comment by blue-melon** [comment]
I think i have the last setup, i downloaded it today on https://www.streamstudio.me/ .

**Comment by smolleyes** [comment]
i made an update to the installer, please retry to download it :)

**Comment by blue-melon** [comment]
seems fixed :)

Thanks

**Comment by smolleyes** [comment]
OK thanks :)
